### ISSUE TITLE
when upload plist file, result message is success but, file content is empty

### ISSUE THREAD

**Issue by leechoohyoung** [PoissonBallon/fastlane-ftp-plugin#7]
every files uploaded completely and the file content is correct except .plist file.

[OTA_template.plist.zip](https://github.com/PoissonBallon/fastlane-ftp-plugin/files/2230532/OTA_template.plist.zip)

**Comment by leechoohyoung** [comment]
O.M.G!
sorry, it was my fault...i did not close file handle.

**Comment by PoissonBallon** [comment]
I close
